version: '3'
services:
  postgres:
    container_name: postgres-CQRS
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: persons
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  api: 
    build: 
      context: ./backend
    container_name: api
    ports: 
      - "3000:3000"

networks:
  postgres:
    driver: bridge

volumes:
  postgres: