server:
  port: 3000
logging:
  level:
    ROOT: info
    org.hibernate.SQL: info
    com.example.cqrs: DEBUG

spring:
  profiles:
    active: 'dev'
  application:
    name: 'CQRS Example'
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB
      file-size-threshold: 2MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: jdbc:postgresql://${POSTGRES_DB:localhost:5432/persons}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true
spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
